default:
  before_script:
    - module purge
    - module load gcc/$GCC
    - module load git cmake python/3
    - module load libcube/4.5 extrap/3
  tags:
    - general

variables:
    GIT_STRATEGY: none
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PIPELINE_ID
