#!/usr/bin/env bash

target=$1

if [ -z "$target" ]; then
	echo "Need to specify a target. Exit."
	echo -e "Usage:\ncgc target.[c|cpp]"
	exit -2
fi

clangversion=$(clang --version | awk '{print $3}' | head -n 1)
clangpath=''

if [ -z "$CLANG_BASE_PATH" ]; then
  echo "Please export CLANG_BASE_PATH to point to the root folder of the clang 10 or 14 installation"
	echo "Current binary is: " $(which clang)
	exit -1
else
  clangpath=$CLANG_BASE_PATH
fi

shoulddebug=false

collectorCommand="cgcollector --capture-ctors-dtors --extra-arg=-I$clangpath/lib/clang/$clangversion/include $target"

if [ -z "$shoulddebug" ]; then
  echo "Running command $collectorCommand"
fi

$collectorCommand

